version: '3.8'
services:
  node:
    image: node:20
    command: bash -c "npm start"
    stdin_open: true
    working_dir: '/app'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      - PORT=3000
